# Generated by Django 5.0.6 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
