# Generated by Django 5.0.6 on 2024-05-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Img',
            new_name='img',
        ),
    ]
